---
- name: restart docker
  command: /bin/true
  notify:
    - reload systemd
    - reload docker

- name : reload systemd
  shell: systemctl daemon-reload
  when: ansible_service_mgr == "systemd"

- name: restart weave
  command: /bin/true
  notify:
    - reload systemd
    - reload weave

- name: restart weaveproxy
  command: /bin/true
  notify:
    - reload systemd
    - reload weaveproxy

- name: restart weaveexpose
  command: /bin/true
  notify:
    - reload systemd
    - reload weaveexpose

- name: reload docker
  service:
    name: docker
    state: restarted

- name: reload weave
  service:
    name: weave
    state: restarted

- name: reload weaveproxy
  service:
    name: weaveproxy
    state: restarted

- name: reload weaveexpose
  service:
    name: weaveexpose
    state: restarted
