apiVersion: v1
kind: ReplicationController
metadata:
  name: stolon-sentinel
spec:
  replicas: 1
  selector:
    name: stolon-sentinel
  template:
    metadata:
      labels:
        name: stolon-sentinel
        stolon-cluster: "kube-stolon"
        stolon-sentinel: "true"
    spec:
      containers:
      - name: stolon-sentinel
        image: nebirhos/stolon:master
        imagePullPolicy: IfNotPresent
        env:
          - name: SENTINEL
            value: "true"
          # Uncomment this if kubernetes discovery doesn't work on your kubernetes cluster (for example no api service certificates configured or https api serving disabled)
          #- name: STSENTINEL_DISCOVERY_TYPE
          #  value: "store"
          - name: STSENTINEL_CLUSTER_NAME
            value: "kube-stolon"
          - name: STSENTINEL_STORE_BACKEND
            value: "etcd" # Or consul
          - name: STSENTINEL_STORE_ENDPOINTS
            value: "{% for srv in groups['etcd'] %}{{ hostvars[srv]['access_ip'] | default(hostvars[srv]['ip']|default(hostvars[srv]['ansible_default_ipv4']['address'])) }}:2379{% if not loop.last %},{% endif %}{% endfor %}"
          - name: STSENTINEL_KEEPER_KUBE_LABEL_SELECTOR
            value: "stolon-cluster=kube-stolon,stolon-keeper=true"
            # Enable debugging
          - name: STSENTINEL_DEBUG
            value: "true"
          - name: STSENTINEL_KUBERNETES_NAMESPACE
            value: "default"
        ports:
          - containerPort: 6431
