apiVersion: v1
kind: Service
metadata:
  name: postgres-master
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30000
  selector:
    stolon-proxy: "true"
    stolon-cluster: "kube-stolon"
