---
- name: restart calico-node
  command: /bin/true
  notify:
    - reload systemd
    - reload calico-node

- name : reload systemd
  shell: systemctl daemon-reload
  when: ansible_service_mgr == "systemd"

- name: reload calico-node
  service:
    name: calico-node
    state: restarted
    sleep: 10