---
- name: ssh | Overwrite sshd.service file
  template: src=sshd.service.j2 dest=/etc/systemd/system/sshd.service backup=yes
  when: ansible_service_mgr == "systemd"
  notify:
    - reload systemd
    - restart ssh

