apiVersion: v1
kind: ReplicationController
metadata:
  name: farnsworth-stress-test
spec:
  replicas: 1000
  selector:
    app: farnsworth-stress-test
  template:
    metadata:
      name: farnsworth-stress-test
      labels:
        app: farnsworth-stress-test
    spec:
      containers:
      - name: farnsworth
        image: 172.16.7.72/farnsworth
        command:
          - "farnsworth"
          - "stress"
        env:
        - name: POSTGRES_DATABASE_NAME
          value: "farnsworth"
        - name: POSTGRES_DATABASE_PASSWORD
          value: ""
        - name: POSTGRES_DATABASE_USER
          value: "postgres"
