- name: 'Clone Setup repository'
  git:
    repo="https://github.com/mechaphish/setup.git"
    dest="{{ addusers.crs.home }}/setup"
    accept_hostkey="yes"
    update="no"
  become: yes
  become_user: "{{ addusers.crs.name }}"

- name: 'Set shell variables for login user'
  include: shellenv.yml
