apiVersion: v1
kind: Service
metadata:
  name: network-dude
spec:
  selector:
    app: network-dude
  ports:
    - protocol: "UDP"
      port: 1999
      targetPort: 1999
  externalIPs:
    - "{{ ids_vip }}"
