---
- name: restart etcd
  command: /bin/true
  notify:
    - reload systemd
    - reload etcd

- name: reload systemd
  command: systemctl daemon-reload
  when: ansible_service_mgr == "systemd"

- name: reload etcd
  service:
    name: etcd
    state: restarted
