---
- name: delete default docker bridge
  command: ip link delete docker0
  ignore_errors: yes
  notify: restart docker

- name: restart docker
  command: /bin/true
  notify:
    - reload systemd
    - reload docker
    - reload kubelet

- name : reload systemd
  shell: systemctl daemon-reload
  when: ansible_service_mgr == "systemd"

- name: reload docker
  service:
    name: docker
    state: restarted

- name: reload kubelet
  service:
    name: kubelet
    state: restarted
