---
- name: Pause
  pause: seconds=10

- name: reload systemd
  command: systemctl daemon-reload
  when: ansible_service_mgr == "systemd" and restart_apimaster is defined and restart_apimaster == True

- name: Pause
  pause: seconds=5

- name: reload kube-apiserver
  service:
    name: kube-apiserver
    state: restarted
    enabled: yes
  when: (restart_apimaster is defined and restart_apimaster == True) or
        secret_changed | default(False)

- name: Pause
  pause: seconds=5

- name: Enable apiserver
  service:
    name: kube-apiserver
    enabled: yes
    state: started
  when: restart_apimaster is not defined or restart_apimaster == False
